const monedas = [
    {
        "codigo": 1,
        "descripcion": "Peso Colombiano",
        "abreviatura": "COP",
        "simbolo": "$",
        "funcional": true,
        "equivalencia": 1,
      },
      {
        "codigo": 2,
        "descripcion": "US Dólar",
        "abreviatura": "USD",
        "simbolo": "$",
        "funcional": false,
        "equivalencia": 0.00027,
      },
      {
        "codigo": 3,
        "descripcion": "Euro",
        "abreviatura": "EUR",
        "simbolo": "€",
        "funcional": false,
        "equivalencia": 0.00023,
      },
      {
        "codigo": 4,
        "descripcion": "Balboa Panameña",
        "abreviatura": "PAB",
        "simbolo": "B./",
        "funcional": false,
        "equivalencia": 0.00023,
      },
      {
        "codigo": 5,
        "descripcion": "Libra Esterlina",
        "abreviatura": "GBP",
        "simbolo": "£",
        "funcional": false,
        "equivalencia": 0.00019,
      },
      {
        "codigo": 6,
        "descripcion": "Peso Mexicano",
        "abreviatura": "MXN",
        "simbolo": "$",
        "funcional": false,
        "equivalencia": 0.0054,
      },
      {
        "codigo": 7,
        "descripcion": "Nuevo Sol",
        "abreviatura": "PEN",
        "simbolo": "S/.",
        "funcional": false,
        "equivalencia": 0.00104,
      },
      {
        "codigo": 8,
        "descripcion": "Dólar Trinitense",
        "abreviatura": "TDD",
        "simbolo": "$",
        "funcional": false,
        "equivalencia": 0.0018,
      },
      {
        "codigo": 9,
        "descripcion": "Bolivar Fuerte",
        "abreviatura": "VES",
        "simbolo": "$",
        "funcional": false,
        "equivalencia": 0.0011054,
      },
      {
        "codigo": 10,
        "descripcion": "Peso Dominicano",
        "abreviatura": "DOP",
        "simbolo": "RD$",
        "funcional": false,
        "equivalencia": 0.015,
      },
      // {
      //   "codigo": 11,
      //   "descripcion": "Bitcoin",
      //   "abreviatura": "BTC",
      //   "simbolo": "$",
      //   "funcional": false,
      //   "equivalencia": 1,
      // },
      {
        "codigo": 12,
        "descripcion": "Yuan",
        "abreviatura": "CNY",
        "simbolo": "¥",
        "funcional": false,
        "equivalencia": 0.0017,
      },
      {
        "codigo": 13,
        "descripcion": "Guaraní ",
        "abreviatura": "PYG",
        "simbolo": "G",
        "funcional": false,
        "equivalencia": 1.83,
      },
      {
        "codigo": 14,
        "descripcion": "Franco Suizo",
        "abreviatura": "CHF",
        "simbolo": "Fr",
        "funcional": false,
        "equivalencia": 0.00024,
      },
      {
        "codigo": 15,
        "descripcion": "Dólar Canadiense",
        "abreviatura": "CAD",
        "simbolo": "C$",
        "funcional": false,
        "equivalencia": 0.00033,
      }
]

export {monedas};

